apiVersion: v1
kind: Pod
metadata:
  name: host-port-pod
spec:
  containers:
    - name: host-port-app
      image: pbadhe34/my-apps:app2
      ports:
        - containerPort: 8090
          hostPort: 9092
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          hostPort: 6379        